### ISSUE TITLE
Blender crashes when changing Mineways-Path

### ISSUE THREAD

**Issue by PhilippKochendoerfer** [Moo-Ack-Productions/MCprep#106]
*Edit by TheDuckCow:* This issue has been mitigated in v3.2.3 and later releases by removing the ability to directly open user preferences from the "Install X" popup tab. Please upgrade to v3.2.3 for this fix!
---

I used the 'Open Mineways' button and the 'No valid program Path found!' window appearded, because I didn't set it up yet. So I clicked on the 'Open MCprep preferences' button and the preferences opened. But when I clicked on the folder-icon to select the .exe, Blender crashed. (copying the Path in the Text-Field worked!). I also tried to navigate directly to the 'User Preferences' and had no problems.

I repeated this several times and got the same results.

I'm using Blender 2.81a

**Comment by TheDuckCow** [comment]
Thanks for sharing, and very strange indeed - definitely want to eliminate crashes in any way possible. 

I've just replicated your exact steps, and find it is indeed happening on my machine as well (Mac OSX). Confirmed this is happening on Blender 2.82 as well, but is *not* occurring in Blender 2.80. I also confirm from my side that, if I open preferences "normally" or not via this popup operator, and then click the folder icon, blender does *not* crash, so it is very specific to when you open preferences via this popup. 

For your context, I'm not sure exactly what to do here other than remove the button in the popup to force people to go there manually (the scenario where it doesn't crash). The folder-pressing icon is actually a built in Blender feature, not something I can really code or modify, so I'll likely be trying to submit a bug to the Blender Foundation on this issue. 

For that purpose, it's helpful to have more information. In your blender 2.81a instance, can you go to Help > system info, and then save the text file somewhere to then copy paste or upload here?

**Comment by PhilippKochendoerfer** [comment]
[system-info.txt](https://github.com/TheDuckCow/MCprep/files/4235397/system-info.txt)

**Comment by TheDuckCow** [comment]
Thanks for sharing, and that helps affirm it's cross platform. I'm working on compiling a bug report for the blender dev team with a simplified code example.

**Comment by StandingPadAnimations** [comment]
Going through some old bug reports to allow us to revisit them. Assuming this has been fixed, I'll close this now
