### ISSUE TITLE
i18n support (adding translations)

### ISSUE THREAD

**Issue by chisaato** [Moo-Ack-Productions/MCprep#165]
I like this addon and if it has i18n support, it will more easy for user to learn it

**Comment by TheDuckCow** [comment]
Thank you for calling out the need for internationalization support! Agreed, this should be a top priority for making this more usable. Will use this space to reference exploration of the "right" way to support i18n. For now, referencing this thread on [another repository](https://github.com/CGCookie/blender-addon-updater/issues/28) I help maintain.

**Comment by ttrtty5** [comment]
> I like this addon and if it has i18n support, it will more easy for user to learn it

https://www.bilibili.com/video/BV1Wa4y1s7ti
如果你需要的是中文翻译，这个视频里有翻译的软件，可以翻译mcprep
blt可以翻译到其他语言，但是因为开发者忙于工作，所以仅限于中文
我的英语水平很烂，所以写了两遍
If you need Chinese translation, there is translation software in this video, you can translate mcprep
blt can be translated to other languages, but because the developer is busy with work, it is limited to Chinese
My English is poor, so I wrote it twice

**Comment by TheDuckCow** [comment]
Bumping this back up, I think it would be good to start working on this in a parallel branch.
There may be a few ways to approach translations, but here is at least [one example](https://raw.githubusercontent.com/johnroper100/CrowdMaster/master/cm_translations.py) using the built in blender setup for string mapping.

**Comment by StandingPadAnimations** [comment]
I think I'll get started on this

**Comment by StandingPadAnimations** [comment]
So I found a guide on localization. Blender provides an API for it:
https://b3d.interplanety.org/en/localization-of-blender-add-ons-with-api/

Just need to confirm this works in 2.78+. If it doesn't, there's also an older way:
https://b3d.interplanety.org/en/localization-of-blender-add-ons/

**Comment by StandingPadAnimations** [comment]
Only problem is that now, we need to manually translate different parts of MCprep, there's no automatic translation

**Comment by StandingPadAnimations** [comment]
So I think what we could do is have a bunch of JSON files (with the name set to the language in question), with the following format:
```json
{
    "language" : "<language here>", 
    "translation"  : {
        "<insert something from the UI>" : "<translation>" 
    }
}
```

That way users wanting to translate only need a text editor (even Notepad works in this case). MCprep could then load these JSON files at startup

Of course opening up translations to the userbase also runs the risk of Google Translate (or something simillar) being used, but that's whole other discussion

**Comment by StandingPadAnimations** [comment]
I've now opened a GitHub issue to track progress on this (#439) and have started work on i18n support for MCprep 3.5.1 (so not next release, but the release after next)

**Comment by StandingPadAnimations** [comment]
I'll close this as completed since we've gotten preliminary support, which we'll be expanding on in the next couple of releases.
