### ISSUE TITLE
Support Octane Renderer (or create fitting materiels)

### ISSUE THREAD

**Issue by TheGreyDiamond** [Moo-Ack-Productions/MCprep#237]
Maybe add support for the octane renderer for Blender. This would improve my and others live a lot, because I have to manually change all materials.

**Comment by StandingPadAnimations** [comment]
While Octane support would be interesting, it's a pretty niche thing and not many people use it. However, MCprep is open-sourced so you can always make a Octane version of MCprep

**Comment by TheDuckCow** [comment]
Indeed, there are a few different alt render engine requests that I have not been able to get to.

However, it may be that the "Sync materials" function inadvertently covers your needs. It would require a one-time setup of materials for the engine and a given resource pack, but then you can reuse it as many times after that in other files, so long as "sync materials" is ticked. 

Let me know if you need more information than here: https://github.com/TheDuckCow/MCprep#sync-materials
I haven't made a video tutorial yet, but it's on my list to get to, as I see it's a seldom used but very powerful feature of MCprep.

**Comment by StandingPadAnimations** [comment]
Alternatively, we could add an API to MCprep for prepping materials. I've mentioned something like this here: https://github.com/TheDuckCow/MCprep/issues/149#issuecomment-1001099841

**Comment by StandingPadAnimations** [comment]
@TheGreyDiamond just curious, how does Octane handle node editing (as in does it has the same editor as Cycles and EEVEE but with it's own nodes?). Does Octane also support the image texture node Cycles users?

The main reason I'm asking is because I'm curious if the new custom default materials #274 will help your dilemma. It's not fully ready (since I have to change some stuff) but testing with Cycles and Radeon ProRender seems to show that it somewhat works

**Comment by TheGreyDiamond** [comment]
Hey, I'll look into it, I've been very busy recently but I'll check that.

**Comment by StandingPadAnimations** [comment]
With this issue, I'm not sure how we continue with reports like these. There's no easy way to support external engines beyond either hoping that they all have some level of Cycles nodes support, and adding support for every engine would be a huge undertaking for us. 

@TheDuckCow should we keep issues related to external engines open (and then add that to the discussion at #500), or close them on the basis that implementing external engine support is more trouble for what it's worth? Personally, I'm fine with also measuring how much of the userbase actually uses external engines and applying the 5% threshold rule to decide, but let me know what are your thoughts on external engine support for MCprep.

@TheGreyDiamond I think the best route would be to fork MCprep and add support for Octane on your own (while we at upstream decide on what course of action to take). I know in the past, MCprep's material generation was... horrifying to say the least, but MCprep 3.5 massively improved on this front. Here's some reference you might find handy:
https://github.com/Moo-Ack-Productions/MCprep/blob/bd3e1bb44da1218c6b2a08b17de208f7c2fb1cd1/MCprep_addon/materials/generate.py#L1171-L1288

**Comment by StandingPadAnimations** [comment]
Alright since no follow up was given, and there really isn't a good way to add support (nor test) for 3rd party engines, I'll just close this and all issues related to 3rd party engines
