### ISSUE TITLE
ACES Colorspace Support

### ISSUE THREAD

**Issue by TheoBearDB** [Moo-Ack-Productions/MCprep#330]
### Check against existing requests

- [X] I have checked known issues, and my problem is different

### Describe the context

Blender's default color space uses sRGB, which is ok for most, but for those that like to use much wider color gamuts we usually use ACES which is the industry standard. Blender supports ACES with a custom configuration, but with MCPrep it doesn't. When loading in the texture images, the color space nodes on them will use the default ones that Blender has, and not the ACES one when the ACES config is loaded, so all the colors of each material are wrong. This is the same for non-color items like Normals, as they are looking for the "Non-Color" colorspace in Blender, which an ACES config doesn't have.

### How do you imagine your feature works?

Have the add-on check if Blender is using the ACES color space, and when adding in materials to use the corresponding color spaces instead of Blender's default ones.

### What existing workaround (or closest thing to a workaround) do you have today (within Blender, MCprep, or any software)? If there is no workaround, explain why you feel this way.

Current workaround is to replace any instances of "Non-Color" in MCprep_addon/materials/generate.py with "role_data". These are in the following lines: 482, 499, 1117, 1118, 1119, 1251, 1252, 1253, 1853, and 2000. 

You'll also need to change this in util.py, on line 53, and line 57. On line 52, 59, and 60 you'll need to replace the instances of "Non-Colour Data" with "role_data" as well. There's another reference to it in world_tools.py on line 57 as well.

This does make it so that you can't use the blender default ones though.

**Comment by TheDuckCow** [comment]
Thanks for outlining this!

What I need to do on my end now is follow the steps to install the colorspace, and then see what python api indicator I can use to determine that ACES is active. Then, with that available as a utility, anywhere that we would need to change the color space (or perhaps just have a variable string reference to the proper name to use for "non color"), we'll swap it in. This way we don't break backwards compatibly.

**Comment by StandingPadAnimations** [comment]
I'll assign myself to this task

**Comment by TheoBearDB** [comment]
Awesome! It's easy to install ACES, but the original way to do so can muddy up a lot of things in Blender. I'd recommend using this: https://www.youtube.com/watch?v=aw1xjChY_9U

**Comment by StandingPadAnimations** [comment]
I already have ACES on my system so it shouldn't be too bad (and thankfully you've also provided the necessary names which makes this a whole lot easier)

Hopefully I'll be able to get this done by either the end of this week or early next week

**Comment by StandingPadAnimations** [comment]
@TheoBearDB Can you check the new `aces` branch and see if it works? You'll need to download the zip, unzip it, and then zip the `MCprep_addon` folder

**Comment by StandingPadAnimations** [comment]
Here's the ACES build of MCprep
[MCprep_addon.zip](https://github.com/TheDuckCow/MCprep/files/9295482/MCprep_addon.zip)

**Comment by TheoBearDB** [comment]
Looks like it works for the most part, but there's a bit of an issue that's probably pretty specific, but could be good to know. I modified my config.ocio file to allow both Blender's standard view transforms and ACES.

Prepping materials adds the correct color space when using ACES to ACES - ACEScg, but the specular and normal textures are set to Non-Color still. This doesn't seem to be a problem though, as from testing it looks like Blender still uses the data the same way and the textures look correct with either "Non-Color" or "role_data" selected, so I suppose it's a non-issue.

Thanks for doing that! I will say the build you gave there doesn't have any of the meshswap, skin, or spawner .blends in it, just so you know!

**Comment by StandingPadAnimations** [comment]
@TheoBearDB after looking into the issue, it seems like it's an MTL issue. It's mentioned here what exactly causes the issue: https://github.com/TheDuckCow/MCprep/issues/231#issuecomment-1431578239

I'll be pushing a fix later today, just wanted to update you on the situation

**Comment by TheDuckCow** [comment]
Hey @StandingPadAnimations how is this issue looking, do we load the appropriate ACES color map now? I don't have it installed to check, I know we are at least incrementally closer to getting it to work with world importing.

**Comment by StandingPadAnimations** [comment]
We should be able to import with ACES now. Later today, I'll do some proper in depth testing to see what areas we still need to work on.

**Comment by StandingPadAnimations** [comment]
Just following up on this issue, I feel like ACES support was added at some point. @TheoBearDB, is there any areas that MCprep has trouble with regard to ACES, or is it all working well?

**Comment by StandingPadAnimations** [comment]
I'm going to assume ACES support in MCprep is pretty much implemented now. Someone will have to double-check, but I think now it's safe to close this as completed.
