### ISSUE TITLE
incorrect texture for hanging soul_lantern

### ISSUE THREAD

**Issue by Vorm1re** [Moo-Ack-Productions/MCprep#342]
### Did the issue happen after restarting Blender?

- [X] Yes, the issue indeed continued after restarting Blender

### Check known issues

- [X] I have checked known issues, and my problem is different

### What happened?

incorrect texture for hanging soul_lanternincorrect

### What steps are needed to produce the bug?

spawn hanging lantern

### What version of MCprep are you using?

3.4.1

### What version of Blender are you using?

3.2.1

**Comment by TheDuckCow** [comment]
Sorry we missed this. Can you share more details and a screenshot @Vorm1re if you're still having issues? My guess is that you are needing to "animate textures" to fix this problem, but hard to tell without more details.

**Comment by StandingPadAnimations** [comment]
I'm going to assume this is related to #512, so I'll close this for now
