### ISSUE TITLE
Redstone Repeater torches turn into wall redstone torches after Mesh Swap

### ISSUE THREAD

**Issue by Colink02** [Moo-Ack-Productions/MCprep#352]
### Did the issue happen after restarting Blender?

- [X] Yes, the issue indeed continued after restarting Blender

### Check known issues

- [X] I have checked known issues, and my problem is different

### What happened?

With Redstone repeaters the redstone torches within them when Mesh Swapped makes them look like redstone torches on a wall.
Before:
![image](https://user-images.githubusercontent.com/11688661/198407146-3c6d1fdc-c4f4-4832-8fc2-c65450f7e8c4.png)
After:
![image](https://user-images.githubusercontent.com/11688661/198405611-60ef195a-c2e5-46c8-a486-ad4a81ec370a.png)

### What steps are needed to produce the bug?

1) place repeaters in a schematic to mineways
2) prep the materials
3) Mesh swap the object

### What version of MCprep are you using?

MCprep 3.4.1

### What version of Blender are you using?

3.1.2
also tried 3.3.1

**Comment by StandingPadAnimations** [comment]
Was it a schematic or a world file? If the former, then it may be a conversion issue

**Comment by Colink02** [comment]
It was a world file, I was initially going to use a schematic from World-edit but I figured pulling the area from world with Mineways was easier. I converted it with Mineways to an Obj file and imported with MCPrep

**Comment by StandingPadAnimations** [comment]
Have you tried using something like jmc2ob? It tends to have less of these issues

**Comment by Colink02** [comment]
Ok I tried that though it seems to have done worse lol
Before (with JMC2OBJ export):
![image](https://user-images.githubusercontent.com/11688661/198480593-ea901833-885e-4095-900a-af0c7d223e74.png)
After Mesh Swap:
![image](https://user-images.githubusercontent.com/11688661/198480945-ed2af73a-8d81-4542-aa0f-5f5ec302d363.png)
After Mesh Swap (without moving the orgin to mass):
![image](https://user-images.githubusercontent.com/11688661/198482367-6535e292-601b-47cf-bb6f-19673aad0849.png)

**Comment by TheDuckCow** [comment]
The source issue with jmc2obj in this scenario I think is actually due to mesh optimization being _on_, for Meshswap to work, all vertices in the original mesh need to be there and not be cleaned up. It's a toggle option inside jmc2obj. Give that a go if you can.

**Comment by Colink02** [comment]
Ok so that fixed the weird redstone lamps being one, so now its only the redstone repeaters being slanted
![image](https://user-images.githubusercontent.com/11688661/198501794-3cb5043b-31d1-423d-af53-dc0273586fc5.png)

**Comment by StandingPadAnimations** [comment]
I'm just going to close this, since there hasn't been reports related to this from other users. You'll still be able to comment
