### ISSUE TITLE
Wolf.

### ISSUE THREAD

**Issue by MrTerroChain** [Moo-Ack-Productions/MCprep#409]
### Name of asset submission

Well, I just changed your wolf and now I'm ready to share. It's Wolf. https://cdn.discordapp.com/attachments/784399899797487626/1089522099669966848/wolf.blend

### Quality checks

- [X] I have used only vanilla textures (or created images that are derived from vanilla textures)
- [X] This is a vanilla minecraft asset/mob/effect
- [X] I have verified my asset has the correct scale (1 Blender unit = 1 meter), and the scale has been applied (control+a, scale)
- [X] If my asset includes a rig, I certified there is a "root" or "main" bone, and the rig object name ends with the name ".arma" or ".rig" to work well with MCprep
- [X] I am the sole creator of this rig, other than any textures by Mojang. Any custom textures I created myself.

### Describe any usage details

None.

### What name should we use to credit you in the README.md file?

MrTerroChain.

### What credit url should we use to reference you in the README.md file?

https://www.youtube.com/@MrTerroChain.

### Confirmation

- [X] By submitting this asset, I affirm the asset is of my own creation. I understand this asset will be included with MCprep with a CC-BY (attribution) license agreement, and that users of MCprep should refer to [MCprep's readme](https://github.com/TheDuckCow/MCprep#credit) for credit or directly name me for credit when this rig is used.

**Comment by TheDuckCow** [comment]
Sorry for the long delay to actually review this rig, we've been stretched thin. @MrTerroChain could you clarify what your version intends to provide as additional value to the existing rig?

At the moment, opening the rig in Blender 3.6 or 2.80 both seem to have fewer bone controls and the head doesn't rotate when rotating the intuitive head bone. I'm inclined to go with the current wolf rig we have in MCprep, but if there's specific reasons why your submission is an improvement, please let us know and then we can give tactical feedback to get it up to standard for inclusion.

**Comment by TheDuckCow** [comment]
Following up here @MrTerroChain to see if you can help respond to the question above - would hate to discard your work, but want to make sure the value added is clear! Thanks

**Comment by StandingPadAnimations** [comment]
Following up again, we'd hate to discard the rig, but we'll have to if no follow up is given

**Comment by TheDuckCow** [comment]
Closing this for now, will happily re-open later if available!
