### ISSUE TITLE
Skin from username not working

### ISSUE THREAD

**Issue by iPanic-Dev** [Moo-Ack-Productions/MCprep#417]
### Did the issue happen after restarting Blender?

- [X] Yes, the issue indeed continued after restarting Blender

### Check known issues

- [X] I have checked known issues, and my problem is different

### What happened?

Using MCprep on Blender 3.5 the skin downloader by username is non-functional. When you attempt to enter a username, and click ok it pauses for a moment and then an error appears that the `Error: Material could not be updated`. 

### What steps are needed to produce the bug?

- Load Blender 3.5
- Navigate to the skins tab, and select `Skin from username`
- Enter a valid username, and click `confirm`. 

### What version of MCprep are you using?

MCprep 3.4.3

### What version of Blender are you using?

Blender 3.5

**Comment by StandingPadAnimations** [comment]
(Sorry for the extremely late response, we've been spread thin recently)

Are you using an MCprep rig? Skin swap only supports MCprep rigs

**Comment by StandingPadAnimations** [comment]
Closing since there hasn't been an update, but you'll still be able to comment
