### ISSUE TITLE
Warden Rig Submission

### ISSUE THREAD

**Issue by DS9448** [Moo-Ack-Productions/MCprep#420]
### Name of asset submission

Warden Rig
[Warden Rig V2.zip](https://github.com/TheDuckCow/MCprep/files/11410633/Warden.Rig.V2.zip)

### Quality checks

- [X] I have used only vanilla textures (or created images that are derived from vanilla textures)
- [X] This is a vanilla minecraft asset/mob/effect
- [X] I have verified my asset has the correct scale (1 Blender unit = 1 meter), and the scale has been applied (control+a, scale)
- [X] If my asset includes a rig, I certified there is a "root" or "main" bone, and the rig object name ends with the name ".arma" or ".rig" to work well with MCprep
- [X] I am the sole creator of this rig, other than any textures by Mojang. Any custom textures I created myself.

### Describe any usage details

The gear icon next to the head has some properties that can be accessed through the 'item' tab in the side menu.

### What name should we use to credit you in the README.md file?

DS_9448

### What credit url should we use to reference you in the README.md file?

https://www.youtube.com/channel/UCSh4JBglkwdiMW__MvF9lPw

### Confirmation

- [X] By submitting this asset, I affirm the asset is of my own creation. I understand this asset will be included with MCprep with a CC-BY (attribution) license agreement, and that users of MCprep should refer to [MCprep's readme](https://github.com/TheDuckCow/MCprep#credit) for credit or directly name me for credit when this rig is used.

**Comment by StandingPadAnimations** [comment]
@DS9448 can we receive a follow-up on this?

**Comment by StandingPadAnimations** [comment]
Since there hasn't been a follow-up on this, and has passed through the whole 3.5.X release cycle, I'll be closing this. @DS9448 if you still want this to be part of MCprep, please create a new submission request
