### ISSUE TITLE
Migrate to the unittest library

### ISSUE THREAD

**Issue by TheDuckCow** [Moo-Ack-Productions/MCprep#424]
There are many frameworks out there, but I've professionally been using unittest for nearly 6 years at this point and so I'm familiar with how it works and, most substantially, appreciate that it's build in (including into blender's python installs itself).

The goal here is to remake the custom test suite runner so it uses the unittest library for more cross platform support and standard convention. Lots of benefits of doing this:

- We can actually mock libraries and functions on the fly, something that has inhibiting good testing design so far
- Can have subtests and have tests continue even past the first failure (we have a number of daisy chain checks right now, which will just fail on the first check even though having all checks within the test share their output would be valuable)
- We can use this as the opportunity to make the test runner actually cross compatible. 
- We can have tests put into multiple files, structured in folders even to parallel MCprep structure itself (I find this very helpful in other projects I'm working on).

... we'll lose the color formatting the test suite, which tbh I actually quite like. But that's pretty minor, I'd rather.

The scope and requirements for the option here:

- Should be able to run a simple file like `run_tests.py`, which is it cross platform and just called with any python3 version installed.
    - Should take the same args [as today's](https://github.com/TheDuckCow/MCprep/blob/master/test_files/addon_tests.py#L2513) (maybe renamed, maybe adjusted how the function). Again, using argparse for improve ease and readability and functionality.
- This test _manager_ should then in a loop, go through all blend files in `blend_execs.txt` with a single call to `test_runner.py`, which will manage the auto discovery (or whatever setup we use) to get tests going. I've done this a few times and can help as needed.
- This test manager should append its results to a text file, concatenating all the test function names that failed into a single line next to the blender version (so that when testing across multiple versions, we can very easily see what failed maybe in some blender versions but not in others).
- Should not suppress the output of
- Should have a way to specify tests input; ie the class or even specific test method name. This way, we can run a single unittest across all versions of blender or even a single version of blender.

This should likely be split into a couple chained PRs. The first one should not delete the current tests, but rather:
- Establish the run_tests.py, test_runner.py, and an initial file which executes a single simple tests (enabling/disabling the addon).
- Has the right args in place

Thereafter, we can spend time refactoring the existing tests to be in different files based on their area of MCprep, so it's not one giant test file. Final step and PR would be to delete the existing run tests, but they should stick around until the full migration has happened.

**Comment by TheDuckCow** [comment]
FYI @StandingPadAnimations on this one. This I see as a much bigger priority than code formatting, as it is of utmost importance that it's easy for anyone to execute tests (and be confident releases are working). Do you have any interest in working on? If so, I can share some sample structure code. If not, I could probably get to the bulk of this next week.

FYI a number of tests on the milestone branch are currently broken, so we should probably fix those _before_ trying to reinvent the test suite.

**Comment by StandingPadAnimations** [comment]
I think reinventing the test suite would be a good idea right now, since on Linux the test suite does not work at all. That being said, I'm not sure if I can work on it (I can test though)

**Comment by TheDuckCow** [comment]
I agree, and I am probably the only one who _can_ effectively do this right now. I'll see if I can get some time to get started with this. I'll start with the initial framework and check with you if that's working, before I go through and convert each of the individual tests.

**Comment by TheDuckCow** [comment]
Officially done now, all tests migrated and passing.

```
-------------------------------------------------------------------------------
bversion   	ran_tests	ran	skips	failed	errors
-------------------------------------------------------------------------------
(3.6.2)   	all_tests	57	2	0	No errors
(4.0.0)   	all_tests	57	2	0	No errors
(3.5.1)   	all_tests	57	2	0	No errors
(3.4.0)   	all_tests	57	2	0	No errors
(3.3.1)   	all_tests	57	2	0	No errors
(3.2.1)   	all_tests	57	2	0	No errors
(3.1.0)   	all_tests	57	2	0	No errors
(3.0.0)   	all_tests	57	2	0	No errors
(2.93.0)   	all_tests	56	3	0	No errors
(2.90.1)   	all_tests	56	3	0	No errors
(2.80.75)   	all_tests	55	4	0	No errors
tests took 194s to run
```
