### ISSUE TITLE
Block Spawner Dimensions Error

### ISSUE THREAD

**Issue by mguggenheim** [Moo-Ack-Productions/MCprep#429]
### Did the issue happen after restarting Blender?

- [X] Yes, the issue indeed continued after restarting Blender

### Check known issues

- [X] I have checked known issues, and my problem is different

### What happened?

When I spawn blocks via the block spawner, they are coming in at a size of 1.008 instead of 1.

### What steps are needed to produce the bug?

Spawn any block from the block spawner.

### What version of MCprep are you using?

3.4.3

### What version of Blender are you using?

3.5.1

**Comment by StandingPadAnimations** [comment]
> When I spawn blocks via the block spawner, they are coming in at a size of 1.008 instead of 1.

This is a known issue, but it seems to comes from Blender's side.
