### ISSUE TITLE
Mcprep spawning blocks with misplaced textures

### ISSUE THREAD

**Issue by shadowkat11** [Moo-Ack-Productions/MCprep#437]
### Did the issue happen after restarting Blender?

- [X] Yes, the issue indeed continued after restarting Blender

### Check known issues

- [X] I have checked known issues, and my problem is different

### What happened?

So I wanted to start getting into Minecraft animation, so I got mcprep. It started off fine when I was just posing my skin, but when I wanted to start animating scenes, and placed blocks like a crafting table or a grass block (which all have multiple textures instead of just a one texture block like a wood plank), they came out misplaced. I've tried lots of things, including redownloading blender and re-installing mcprep, but couldn't get it fixed.  
Any way to fix this?
![little texture bug](https://github.com/TheDuckCow/MCprep/assets/138401185/23be9a7d-28c9-479e-92af-4d177036199e)

### What steps are needed to produce the bug?

All that is needed to make it (for me) is to find a block with multiple textures (ex. grass, it has the sides, top, and bottom) and to place it, as the textures will be in the incorrect places.

### What version of MCprep are you using?

Mcprep 3.4.3

### What version of Blender are you using?

Blender 3.6

**Comment by StandingPadAnimations** [comment]
This is a known issue, we're not sure what causes it

**Comment by shadowkat11** [comment]
alr, thanks for the answer anyway.
