### ISSUE TITLE
can't tick the box

### ISSUE THREAD

**Issue by ender-guardian** [Moo-Ack-Productions/MCprep#447]
### Did the issue happen after restarting Blender?

- [X] Yes, the issue indeed continued after restarting Blender

### Check known issues

- [X] I have checked known issues, and my problem is different

### What happened?

I installed the MCprep addon into the blender addons, and when I tried to tick the box, nothing happened. there was no error message or anything of the sort. just nothing happened, and no box was ticked.

### What steps are needed to produce the bug?

i downloaded mcprep and installed it into blender; when i tried to tick the box it didn't work

### What version of MCprep are you using?

idk, i think the latest version

### What version of Blender are you using?

also the latest version

**Comment by StandingPadAnimations** [comment]
> idk, i think the latest version

If you're not sure, then I suggest re-downloading MCprep (https://github.com/TheDuckCow/MCprep/releases/tag/3.4.3) and trying again

> also the latest version

"Latest version" changes as time passes (and a lot of people are unaware of new Blender releases), so we need the version number

**Comment by ender-guardian** [comment]
i tried your link, but it didn't change anything, thanks anyway though. btw, i downloaded both mcprep and blender a few days ago and there was no new update since.

**Comment by StandingPadAnimations** [comment]
We still request the version number. A "few days ago" is not sufficient as a lot of people download older versions of Blender or alpha versions. As far as we're concerned, downloading "the latest version a few days ago" could mean (and yes you'll be surprised what other people do):
- Downloading an older release someone linked (like Blender 2.7x in the case of the BPS tutorial) without knowing of any additional releases
- Downloading an alpha or beta release 

In addition, MCprep works fine on my end in Blender 3.6 (and I'm not sure why Blender wouldn't allow an addon to be enabled without any error), but again I have no idea if you're using 3.6, some older version by mistake, or some alpha version like 4.0 (where MCprep is known to have issues).

**Comment by TheDuckCow** [comment]
As just a sanity check @ender-guardian did you manage to [follow this video](https://www.youtube.com/watch?v=Z8fMRFAXG-k&list=PL8X_CzUEVBfaa9PD9lWm4HdQCxUhl62Zb&index=2) exactly? Indeed would be odd to not have an error pop up at least on pressing the tick box.

**Comment by StandingPadAnimations** [comment]
Closing as no updates have been made since July. @ender-guardian, if you still have this problem, you can comment on this report even after closing
