### ISSUE TITLE
Why are individually spawned blocks 1.008 meters? And is there a way to change this?

### ISSUE THREAD

**Issue by FigureOfStickman** [Moo-Ack-Productions/MCprep#451]
<img width="245" alt="Screenshot 2023-07-24 at 7 06 08 PM" src="https://github.com/Moo-Ack-Productions/MCprep/assets/54049252/bd044b44-cd3b-4f21-89b1-11cc99cefec7">

**Comment by StandingPadAnimations** [comment]
Closing since this doesn't use the bug report template. That being said, this is already a known issue, but lies in Blender's `bmesh` module (what we use to generate blocks) and thus is beyond fixing
