### ISSUE TITLE
Code to manually offset bmesh's scaling problem. It's messy in principle but it works perfectly.

### ISSUE THREAD

**Issue by FigureOfStickman** [Moo-Ack-Productions/MCprep#452]
### bmesh scale fix

Hi! I hope this isn't inappropriate. I've never really used GitHub before.

I added this bit of code in my copy of the addon to rescale spawned blocks so that they aren't 1.008m^3. It's been working great so far, so I thought you guys may want to check it out. It's been bothering my adderall-riddled brain and [StandingPadAnimations said it was a known issue.](https://github.com/Moo-Ack-Productions/MCprep/issues/451#issuecomment-1648790199)

Here's a screenshot of the code I added to [mcmodel.py](https://github.com/Moo-Ack-Productions/MCprep/blob/a8facb4a3b8fd7f0f5d22577e4d53a57f742190a/MCprep_addon/spawner/mcmodel.py#L4) and what it looks like in Blender. I guess it automatically applies the scale because the operation is being performed on the raw mesh, so that cleans it up a bit for the user.

<img width="742" alt="moddedmcprep" src="https://github.com/Moo-Ack-Productions/MCprep/assets/54049252/9ca2bca8-0d33-43d2-9405-0c636d4c4866">
<img width="405" alt="Screenshot 2023-07-25 at 11 45 52 AM" src="https://github.com/Moo-Ack-Productions/MCprep/assets/54049252/14c78d18-61fd-4969-b3d7-663af89af727">

### Quality checks

- [X] I have used only vanilla textures (or created images that are derived from vanilla textures)
- [X] This is a vanilla minecraft asset/mob/effect
- [X] I have verified my asset has the correct scale (1 Blender unit = 1 meter), and the scale has been applied (control+a, scale)
- [X] If my asset includes a rig, I certified there is a "root" or "main" bone, and the rig object name ends with the name ".arma" or ".rig" to work well with MCprep
- [X] I am the sole creator of this rig, other than any textures by Mojang. Any custom textures I created myself.

### Describe any usage details

Not a rig, I hope it's still okay for me to submit this though.

### What name should we use to credit you in the README.md file?

FigureOfStickman

### What credit url should we use to reference you in the README.md file?

youtube.com/@figureofstickman6718

### Confirmation

- [X] By submitting this asset, I affirm the asset is of my own creation. I understand this asset will be included with MCprep with a CC-BY (attribution) license agreement, and that users of MCprep should refer to [MCprep's readme](https://github.com/TheDuckCow/MCprep#credit) for credit or directly name me for credit when this rig is used.

**Comment by zNightlord** [comment]
This is more a code thing so better off create a Pull Request.
But first I think you could try out poking around 
[mcmodel at line 66](https://github.com/Moo-Ack-Productions/MCprep/blob/a8facb4a3b8fd7f0f5d22577e4d53a57f742190a/MCprep_addon/spawner/mcmodel.py#L66) I kinda talked about it in the Discord server. It is the source list of how the model verticies is made.
For your way, the block model spawn isn't just for block model, you can import any Minecraft Java json model into and have it will be slightly scale if you do that.

**Comment by StandingPadAnimations** [comment]
Thanks for submitting code! Like zNight said, this falls under Pull Requests (which are designed for code). I'd suggest reading https://github.com/Moo-Ack-Productions/MCprep/blob/dev/CONTRIBUTING.md for some more info. 

One thing I'd suggest (just from looking) is checking to see if a particular dimension is close to 1m before resizing. Some blocks like slabs for example will be 1m for X and Y, but not Z. Perhaps a simple "threshold" value that goes "if the dimension minus 1 is less then this threshold, then resize it to 1. Beyond that, I'll save further reviewing for a pull request
