### ISSUE TITLE
Cloud Shader tweak Proposal

### ISSUE THREAD

**Issue by 4nyNoob** [Moo-Ack-Productions/MCprep#463]
### Check against existing requests

- [X] I have checked existing feature requests, and my idea is different

### Describe the context

I'd like to improve the could shaders on mcprep a tiny bit by making it more similar to the minecraft's ones at least on cycles, here's some screenshots of the results, a screenshot of the game and the node group that made it possible

### DEFAULT SHADER
![image](https://github.com/Moo-Ack-Productions/MCprep/assets/113947854/aeb7f236-3d1a-4415-910c-ad3c1542da01)

### PROPOSAL
![image](https://github.com/Moo-Ack-Productions/MCprep/assets/113947854/96f553f6-40e2-4bdf-89b4-ce5473d07449)

### MINECRAFT'S CLOUDS
![image](https://github.com/Moo-Ack-Productions/MCprep/assets/113947854/77c6c2bf-a2d7-4707-8b8b-c22e9db908f9)

## FINAL NODEGROUP
![image](https://github.com/Moo-Ack-Productions/MCprep/assets/113947854/31d5696b-7036-4de9-a64d-429c530fc573)

### How do you imagine your feature works?

We would need to make the check if the user is using cycles or eevee and use my proposed shader if the user is using cycles

### What existing workaround (or closest thing to a workaround) do you have today (within Blender, MCprep, or any software)? If there is no workaround, explain why you feel this way.

every time I'm making a minecraft render i need to modify the cloud shader manually in order to have a more accurate look of the cloud's shader on cycles

**Comment by StandingPadAnimations** [comment]
Thanks for the submission. We're already nearing the end of the MCprep 3.5 development Cycle, so we can't include it for the next MCprep release. However, I've added this proposal to the list for the MCprep 3.5.1 development cycle

**Comment by StandingPadAnimations** [comment]
@4nyNoob Since we're now in the 3.5.2 cycle (3.5.1 was a patch release for 4.0, so we couldn't include anything new), I'm curious how the new clouds look in different "conditions" (for the lack of a better term). Can you demonstrate how the new clouds look at other times of day, like sunrise or sunset?

**Comment by TheDuckCow** [comment]
Just made these changes locally, a really nice improvement! Still works with the distance falloff as well, which is great. And works as expected in blender 2.80  and 4.0 (for cycles only, of course; Eevee's currently solution of using blend seems to work nicely as-is).

Closing this as complete, these files will be included in the next MCprep release.

[updated_cloud_moon_files.zip](https://github.com/Moo-Ack-Productions/MCprep/files/13773104/updated_cloud_moon_files.zip)
