### ISSUE TITLE
Item Frame (block)

### ISSUE THREAD

**Issue by Zachadactyl** [Moo-Ack-Productions/MCprep#468]
### Did the issue happen after restarting Blender?

- [X] Yes, the issue indeed continued after restarting Blender

### Check known issues

- [X] I have checked known issues, and my problem is different

### What happened?

Spawning in an item_frame block model from the spawner imports the right geometry but an improper texture.  The frame edges are linked to the right texture, but UV mapped a bit small and inset some.  The center of the frame is set to use birch_planks texture. but is an easy fix/rescale.  

### What steps are needed to produce the bug?

1) Make a new Blender 3.6.2 project
2) Import item frame from Block (model) Spawner

### What version of MCprep are you using?

MCprep 3.4.3

### What version of Blender are you using?

Blender 3.6.2

**Comment by zNightlord** [comment]
Might be related to #437, need confirmation on that.

**Comment by StandingPadAnimations** [comment]
Based on the description (screenshots will be helpful), it's indeed related to #437

**Comment by zNightlord** [comment]
Since #437 is resolved now, assuming it is that. Closing this.
