### ISSUE TITLE
Versioning Proposals

### ISSUE THREAD

**Issue by StandingPadAnimations** [Moo-Ack-Productions/MCprep#474]
I have 2 proposals here regardding future MCprep versioning:
- Add “reserved” version components
- Switch to Calendar Versioning (what I honestly would prefer)

# Reserve Version Components
With MCprep's new RC system, I propose we reserve the `patch` component for release canidates, so the first RC of MCprep 3.5 would be `MCprep 3.4.3.1`. This way, we still have room to make an update in an MCprep series. Note this would only apply to `__init__.py`, Git tags would just be `#.#.#-rc-#`.

# Calendar Versioning
MCprep is a large addon, and it's now pretty difficult to decide when a release is “major” (frankly, all releases are major releases these days). MCprep 3.5 for instance will be a “minor” release, despite having the biggest changes overall. In addition, with the introduction of release candidates, it's even harder to make room in the current semantic versioning scheme (the 3.5 release candidates used the “patch” part, but what happens when we actually need that patch part for a stable release?).

I suggest we switch to [Calendar Versioning](https://calver.org) for MCprep 4.0, so that release numbers are based on when the release is made. Under this system, MCprep versions would be based on year and month.
`MCprep YYYY.MM`

MCprep release candidates would add `99` to a 3rd component, and then the 4th component would the the RC number
`MCprep YYYY.MM.99.##`

Using MCprep 3.5 for example, under Calendar Versioning it would be `MCprep 2023.09` (if we go by our current plan to release it this month). In addition, MCprep 3.5 RC-1 would be `MCprep 2023.08.99.1` (where `99` signifies RC, and `1` signifies the first RC).

## Referring to In-Development Versions
Of course, the question now is how would we refer to in development versions of MCprep. For that, we can set a goal year and month. This puts higher pressure on us, but with #465, that shouldn't be that much of an issue anyway.

## Concerns about Breakage
I don't think this will affect the addon updater much. The addon updater checks if a tag is greater than the tag of the current version, and `2023` is definitely higher than `3` or `4`.

**Comment by TheDuckCow** [comment]
I support the approach for versioning. Using the sub patch version is unofficially what we do currently anyways. Id say that as soon as a release is made, the dev branch should automatically get incremented by 0.0.0.1 in all cases (and if we have multiple RC's then we can do it again).

Regarding versioning, I'm still more in favor of the current system, but we could spell out the logic I've implicitly been using for numbering. For a version made up of (major, minor, patch, sub-patch/rc):

- Major increment:
  - A complete rewrite. We're less likely to have a rewrite; even our 3.5 release felt major but wasn't truly a full rewrite.
  - A _substantial_ UI overhaul, which clearly indicates that tutorials and guides will be outdated or not easy to follow. We expect that the update will result in users needing to re-learn parts of the workflow, as hard as we might try to make it intuitive. Means tutorial series would need to be re-released. In the MCprep world, this would be equivalent to blender's own transition 2.7 to 2.8, but would probably not include (from a UI/UX standpoint) the transition from 2.9 to 3.0.
- Minor increment:
  - Ironically named "minor", this is still for major updates, just not those that don't hit the criteria above.
  - Big new features or new workflows introduced.
  - Existing workflows or settings changes; potential breakage in backwards compatibility in terms of operator properties renamed or changed in terms of behavior. 
  - Anything that would require a tutorial or help page on a given feature to need updating.
- Patch increment:
  - Minor features added that , bugs fixed to implement originally intended functionality.
  - Should not require any documentation updates (aside from maybe removing a "this isn't working as intended" callout if one exists)
- sub-patch/rc:
  - As mentioned, reserved for development and release candidates. Release candidates should numerically still be underneath the version we are targeting. So indeed, 3.4.2.2 would turn into either 3.4.3 or 3.5.0 (depending on the rules above; in our present case, clearly we're going with 3.5.0)

**The cons of a date-based versioning:** It doesn't help tell the user at all how important the release is. Yes, MCprep has had a slow release cadence, but the version naming convention still has been following 9roughly) the guidelines above and thus it's clearer where the big changes are version-wide. Plus, we hope the increase the rate of releases and maybe even adopt more automation when performing releases, so having clearer guidelines on the versioning will be important.

Pretty much if you think of an app store, apps that user date based versioning that push out builds every two weeks are hard to motivate customers to update or even creates update fatigue. Let me know your thoughts @StandingPadAnimations.

**Comment by StandingPadAnimations** [comment]
I would personally move backwards compatibility breakage to major releases, just as that's how it is for most software. Other than that, looks fine to me.

**Comment by StandingPadAnimations** [comment]
Closing as complete (in terms of what has been decided)
