### ISSUE TITLE
When I try to render my scene, blocks like amethyst and rails don't render correctly

### ISSUE THREAD

**Issue by Tuftyy** [Moo-Ack-Productions/MCprep#482]
### Did the issue happen after restarting Blender?

- [X] Yes, the issue indeed continued after restarting Blender

### Check known issues

- [x] I have checked known issues, and my problem is different

### What happened?

When I try to render my scene, rails and amethyst won't render properly. This happens for most 2d models

![image](https://github.com/Moo-Ack-Productions/MCprep/assets/145628963/0f6a4adc-a319-418e-8374-3e39cb94b9c1)

### What steps are needed to produce the bug?

I have no idea, one day I just opened blender after about a week or maybe two and it just wouldn't work

### What version of MCprep are you using?

3.4.3

### What version of Blender are you using?

Blender 3.2

**Comment by StandingPadAnimations** [comment]
This is due to how Mineways (assuming you're using Mineways) exports worlds. To fix this, select your OBJ, go into edit mode, press M and then the "By Distance" option

**Comment by Tuftyy** [comment]
What you said worked! Thank you so much

**Comment by StandingPadAnimations** [comment]
Alright I'll close this then
