### ISSUE TITLE
Use emissions tick box does not show up in the settings of swap texture pack

### ISSUE THREAD

**Issue by Jaitie018** [Moo-Ack-Productions/MCprep#493]
### Did the issue happen after restarting Blender?

- [X] Yes, the issue indeed continued after restarting Blender

### Check known issues

- [X] I have checked known issues, and my problem is different

### What happened?

No enable or disable emissions tick box
![image](https://github.com/Moo-Ack-Productions/MCprep/assets/73315227/2aabe5c0-1b49-414c-8265-b9fda6d3b7d2)

### What steps are needed to produce the bug?

Click on mcprep's Swap texture pack

### What version of MCprep are you using?

3.5.0

### What version of Blender are you using?

3.6.4

**Comment by zNightlord** [comment]
I can confirm the the UI inconsistency issue. 
The code for drawing prep material UI and the one in swap texture aren't shared at the moment.

**Comment by Jaitie018** [comment]
omg hi znight

**Comment by StandingPadAnimations** [comment]
@zNightlord do you think we can get this done soon? I've put it in the 3.6.1 milestone, but I'd rather for this to be fixed in time for 3.6 so we don't forget. If needed, I can create a PR for this as soon as possible

**Comment by TheDuckCow** [comment]
Wow, the LOC to days of ticket open is quite a number to behold, thanks for getting to this one. Merged into dev now, will be in the next release.

**Comment by StandingPadAnimations** [comment]
> Wow, the LOC to days of ticket open is quite a number to behold, thanks for getting to this one. Merged into dev now, will be in the next release.

Yeah, I sense we got a good handful of bug reports like that. 3.6.1 would be a good opportunity to go through some old bug reports and work on fixing those issues (assuming they're not already)
