### ISSUE TITLE
MCprep Prep Materials does not support Principled V2

### ISSUE THREAD

**Issue by StandingPadAnimations** [Moo-Ack-Productions/MCprep#494]
### Did the issue happen after restarting Blender?

- [X] Yes, the issue indeed continued after restarting Blender

### Check known issues

- [X] I have checked known issues, and my problem is different

### What happened?

When using MCprep's Load Material function, MCprep will generate the nodes but can't make any connections, due to different inputs in Principled V2.

Principled V2 is an addition to Blender 4.0 and is a rewrite of Principled BSDF, with proper energy conservation among other improvements. It's extremely useful, but also breaks MCprep

![image](https://github.com/Moo-Ack-Productions/MCprep/assets/75058058/b28aa02c-28ca-4038-bd08-1bc697b2d424)

### What steps are needed to produce the bug?

1. Load a blend file
2. Add a mesh or use the default cube
3. Go into `Material Properties > MCprep materials`, select a material, and click Load
4. Find that nodes have been generated but an error occurs due to inputs being incorrect

### What version of MCprep are you using?

MCprep 3.5.0

### What version of Blender are you using?

Blender 4.0 Beta, October 9th build

https://builder.blender.org/download/daily/blender-4.0.0-beta+v40.49c62e8e164c-linux.x86_64-release.tar.xz

**Comment by zNightlord** [comment]
Some sockets were renamed so like Specular and [Emission](https://projects.blender.org/blender/blender/commit/ca5f1c0f008ae703bd00a08919848c766ee76bfb).
Assume that is the problem since we set values before connect the sockets.

[A commit that has all the socket name change](https://projects.blender.org/blender/blender/commit/237dc73ff6c88093907187a18af8dfb5341f84ba)

**Comment by CFeeney333** [comment]
Working on it...

**Comment by CFeeney333** [comment]
#503
