### ISSUE TITLE
traceback error

### ISSUE THREAD

**Issue by toidesingerr** [Moo-Ack-Productions/MCprep#496]
### Check against existing requests

- [X] I have checked existing feature requests, and my idea is different

### Describe the context

when i tried to enable mcprep it said error and traceback

### How do you imagine your feature works?

idk

### What existing workaround (or closest thing to a workaround) do you have today (within Blender, MCprep, or any software)? If there is no workaround, explain why you feel this way.

idk

https://github.com/Moo-Ack-Productions/MCprep/assets/148510165/d6bbfefa-f3ec-42d2-9482-c016aa55587f

**Comment by StandingPadAnimations** [comment]
You need to file a bug report, not a feature request, so I'll have to close this.

**Comment by StandingPadAnimations** [comment]
Also nice Vsauce clip, but it doesn't really help matters here
