### ISSUE TITLE
I can't install the addon into blender

### ISSUE THREAD

**Issue by BBfiChe** [Moo-Ack-Productions/MCprep#507]
### Did the issue happen after restarting Blender?

- [X] Yes, the issue indeed continued after restarting Blender

### Check known issues

- [X] I have checked known issues, and my problem is different

### What happened?

It gives me a whole lot of errors and I don't know why
![image](https://github.com/Moo-Ack-Productions/MCprep/assets/113315299/0cf81f5f-e370-4e66-8fe1-e2370e522a07)

### What steps are needed to produce the bug?

1. Install blender 4.0
2. try to install the mcprep 3.5.1 or another version
3. check the check mark to enable it
4. You get a bunch of errors on screen

(I don't know if blender 4 is supported as it just came out but if it is, sorry I made a ticket and wasted your time.)

### What version of MCprep are you using?

MCprep 3.5.1

### What version of Blender are you using?

Blender 4.0.1

**Comment by StandingPadAnimations** [comment]
The error doesn't indicate an MCprep side problem, try uninstalling completely MCprep and reinstalling

**Comment by StandingPadAnimations** [comment]
Seeing as this report hasn't gotten an update in a while, and the error is a Blender side error, I'll close this now (though comments are still allowed in closed issues in case OP's problem has not been resolved)
