### ISSUE TITLE
TraceBack error || Syntax Error: invalid sytnax

### ISSUE THREAD

**Issue by SzarPis** [Moo-Ack-Productions/MCprep#511]
### Did the issue happen after restarting Blender?

- [X] Yes, the issue indeed continued after restarting Blender

### Check known issues

- [X] I have checked known issues, and my problem is different

### What happened?

when i enable the addon i get an error: traceback error and i have no idea how to solve it
![obraz_2023-12-03_133636986](https://github.com/Moo-Ack-Productions/MCprep/assets/152786675/8c614580-2502-4f19-a254-bfba3a3e832b)

### What steps are needed to produce the bug?

just add the addon

### What version of MCprep are you using?

MCprep 3.5.1

### What version of Blender are you using?

Blender 2.78

**Comment by StandingPadAnimations** [comment]
Indeed, we dropped 2.7x support in MCprep 3.5 as there were too little users using 2.78 and 2.79 to justify continuing to be behind with Python features. You can see the full reasoning behind the move in #399
