### ISSUE TITLE
Blender cleans up object particles sources after collection spawning

### ISSUE THREAD

**Issue by TheDuckCow** [Moo-Ack-Productions/MCprep#515]
A problem I ran into while working on this tutorial, if you save a collection effect whereby the source of a particle system used is an object (as opposed to a collection), it will work right away as an instance in a scene, but after saving and reloading this scene, the source particle gets cleaned up and thrown away.

Using manual inspection, I found we can prevent this by marking the objects used as particle sources as fake users at the object level in the outliner. We just need to do this in code. Honestly, seems like a blender bug and I've run into it before, but I think we only addressed the collection use case before.

The workaround in the meantime is to only author collection effects where any included particle systems only reference collections as the source. The consequence is potentially lost work after coming back to this file - I myself even ran into this after rendering an entire scene

**Comment by StandingPadAnimations** [comment]
Assuming this is a Blender bug, I think it would also be a good idea to report this upstream, just to confirm that it is a bug and not intendee behavior
