### ISSUE TITLE
Error loading the plugin

### ISSUE THREAD

**Issue by MaserPlay** [Moo-Ack-Productions/MCprep#534]
### Did the issue happen after restarting Blender?

- [x] Yes, the issue indeed continued after restarting Blender

### Check known issues

- [X] I have checked known issues, and my problem is different

### What happened?

I tried to run mcprep and saw an error Python: Traceback (most recent call last):
  File "D:\programs\steam\steamapps\common\Blender\4.0\python\lib\genericpath.py", line 19, in exists
    os.stat(path)
TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType

### What steps are needed to produce the bug?

try load mcprep. You will see error: Report: Ошибка Python: Traceback (most recent call last):
  File "D:\programs\steam\steamapps\common\Blender\4.0\python\lib\genericpath.py", line 19, in exists
    os.stat(path)
TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType

### What version of MCprep are you using?

mcprep 3.5.3

### What version of Blender are you using?

blender 4.0 from steam

**Comment by StandingPadAnimations** [comment]
The error indicates something is wrong with `pathlib` (one of the Python modules we use), which means the error is Blender side. The most we can suggest is uninstalling and reinstalling Blender, but that's really it.

**Comment by StandingPadAnimations** [comment]
(Closing since this is a Blender side issue, but you'll still be able to comment)
