### ISSUE TITLE
No bed???

### ISSUE THREAD

**Issue by YTTA-v** [Moo-Ack-Productions/MCprep#535]
### Did the issue happen after restarting Blender?

- [X] Yes, the issue indeed continued after restarting Blender

### Check known issues

- [X] I have checked known issues, and my problem is different

### What happened?

I just try find bed in Block Spawner and materials, I cant find any bed

### What steps are needed to produce the bug?

Just cant find bed in block spawner and MCprep materials

### What version of MCprep are you using?

MCprep 3.5.3

### What version of Blender are you using?

Blender 3.5

**Comment by StandingPadAnimations** [comment]
Beds are entities, which don't define geometry in their respective JSON models, but instead are hardcoded in the Minecraft renderer. As such, we can't spawn them from JSON models like a regular block (see #469 for more details)
