### ISSUE TITLE
Swap Texture pack spews out an error and wont change texture

### ISSUE THREAD

**Issue by Jaitie018** [Moo-Ack-Productions/MCprep#539]
### Did the issue happen after restarting Blender?

- [X] Yes, the issue indeed continued after restarting Blender

### Check known issues

- [X] I have checked known issues, and my problem is different

### What happened?

I import a world using mineways and swapping the texture pack that was correctly working before with Mcprep gives me an error
![image](https://github.com/Moo-Ack-Productions/MCprep/assets/73315227/fab7cccd-09bf-4975-bd0e-03f4880b5bf0)

### What steps are needed to produce the bug?

Import a world, Swap texture pack

### What version of MCprep are you using?

3.5.2

### What version of Blender are you using?

4.0.2

**Comment by StandingPadAnimations** [comment]
This is a bug in `3.5.2` that was fixed in [`3.5.3`](https://github.com/Moo-Ack-Productions/MCprep/releases/tag/3.5.3)

**Comment by Jaitie018** [comment]
ergiohbsdfguiohaerf0ui hgferuiohsdfuio hsdfuio hwerauioher uioherta4790y34  7890y5 347 78&*(^T!@*&(^T@#$*^ Y@#UYG!@ yui IWoWoWoWoWoWoWOWoWoWOWO uiofhuidsfhudfuhfshs sdfwe][pldweq][pldewq][pdlewq][pldewq][pldewq][pldeqw][pldeqw][pldweq
