### ISSUE TITLE
Removing the MCprep Optimizer

### ISSUE THREAD

**Issue by StandingPadAnimations** [Moo-Ack-Productions/MCprep#541]
(mostly copied from https://github.com/Moo-Ack-Productions/MCprep/issues/514#issuecomment-1868565367)

MCprep 3.6 will remove the Cycles optimizer for the following reasons:
- Hasn't caught up with latest Cycles developments
- Algorithm is extremely buggy at times; there's been cases of it setting max bounces to values like 80. Ironically, I don't even use the optimizer (despite making it) for this very reason, and opt to manually optimize my scene
- [Better tools exist](https://pidgeontools.gumroad.com/l/PidgeonToolBag) for automatic optimization; the Super Image Denoiser devs at Pidgeon Tools have SFR, a Cycles optimizer that actually profiles the scene, making it far better then what we have.  
- While the intent of the MCprep optimizer was to have something tuned specifically for Minecraft animation, I feel that over time, that became "how do we optimize a scene while not profiling, due to the average user's hardware?"

**Comment by TheDuckCow** [comment]
Marking this as closed, since the milestone branch has been completed. Will take effect in the next v3.6.0 release
