### ISSUE TITLE
AddColor node purpose

### ISSUE THREAD

**Issue by lynrayy** [Moo-Ack-Productions/MCprep#545]
### Did the issue happen after restarting Blender?

- [X] Yes, the issue indeed continued after restarting Blender

### Check known issues

- [X] I have checked known issues, and my problem is different

### What happened?

Why there are useless AddColor everywhere in prepared materials?
![image](https://github.com/Moo-Ack-Productions/MCprep/assets/59417884/6505f9aa-b657-47ea-846d-f31fab3163a0)

### What steps are needed to produce the bug?

N/A

### What version of MCprep are you using?

3.5.3

### What version of Blender are you using?

3.5.0

**Comment by StandingPadAnimations** [comment]
Add color is used to add color to to blocks, such as grass (whose base color is gray and is added seperately). It has no additional overhead in Blender, nor practical impact render times
