### ISSUE TITLE
blocks not showing up

### ISSUE THREAD

**Issue by Cameraanimater3D** [Moo-Ack-Productions/MCprep#547]
### Did the issue happen after restarting Blender?

- [X] Yes, the issue indeed continued after restarting Blender

### Check known issues

- [X] I have checked known issues, and my problem is different

### What happened?

hey at first i wasn't sure if it was a bug or not since i  never really paid any attention to it but i was working on an animation
where my character had to be mining a block an when i went to go get a block there was only a handful of blocks but then i noticed the problem only happend when i used the barebones pack

### What steps are needed to produce the bug?

1)I dont know it was just there all of a sudden

### What version of MCprep are you using?

Mcprep 3.5.0

### What version of Blender are you using?

Blender 4.0

**Comment by StandingPadAnimations** [comment]
Blocks are sourced from the resource pack being used. It's likely barebones doesn't include JSON models for every block. Not much that can be done
