### ISSUE TITLE
Textures not showing

### ISSUE THREAD

**Issue by jofri99** [Moo-Ack-Productions/MCprep#552]
### Did the issue happen after restarting Blender?

- [X] Yes, the issue indeed continued after restarting Blender

### Check known issues

- [X] I have checked known issues, and my problem is different

### What happened?

When I spawn any mobs or players the textures are not showing
![blenderIssue](https://github.com/Moo-Ack-Productions/MCprep/assets/31164173/c20d5a69-7ccd-40c4-ae41-a0b257e2f260)

### What steps are needed to produce the bug?

Add any mob from the spawner tab

### What version of MCprep are you using?

3.5.0

### What version of Blender are you using?

3.4.1

**Comment by StandingPadAnimations** [comment]
Can you show a screenshot of the entire viewport? I can't tell if this is actually a bug or if it's just the wrong viewport mode

**Comment by StandingPadAnimations** [comment]
I can't reproduce this on my end, so it's likely a case of not being in the correct view mode. Use material mode to view textures.
![image](https://github.com/Moo-Ack-Productions/MCprep/assets/75058058/8770cc7c-f765-419c-8afa-96534bae1a2c)
