### ISSUE TITLE
Swap Texture Packs not working for 1.20.4 experimental worlds

### ISSUE THREAD

**Issue by startFX** [Moo-Ack-Productions/MCprep#573]
### Did the issue happen after restarting Blender?

- [X] Yes, the issue indeed continued after restarting Blender

### Check known issues

- [X] I have checked known issues, and my problem is different

### What happened?

Using the Prep Materials feature on a jMc2Obj 1.20.4 world with experimental settings for 1.21 features enabled w
hile using a custom LabPBR 1.3 resource pack does not work. At the bottom of the screen, there is a popup saying "0 materials affected".
What I excepted to happen was Blender to just Swap the texture pack.

![image_2024-05-10_130645880](https://github.com/Moo-Ack-Productions/MCprep/assets/97802764/92035a70-6ebf-4602-a61b-831a12a4d6a4)

![image_2024-05-10_130704341](https://github.com/Moo-Ack-Productions/MCprep/assets/97802764/7c8ab1b3-1b13-4bfd-8d19-3f0337396380)

![image_2024-05-10_130734796](https://github.com/Moo-Ack-Productions/MCprep/assets/97802764/15ec5c15-e6bf-4b0a-a0a8-457472cd12ba)

### What steps are needed to produce the bug?

1) Export a Minecraft 1.20.4 world using jMc2Obj while making sure new blocks from the trail chambers are being selected.
2) Import the .obj into Blender using the obj world import feature.
3) Prep materials with the default texture.
4) Swap Texture Packs to https://modrinth.com/resourcepack/pixlli/version/jMva4izJ

### What version of MCprep are you using?

MCprep 3.5.3

### What version of Blender are you using?

Blender 4.1

**Comment by StandingPadAnimations** [comment]
This isn't an MCprep bug, this is a bug with your resource pack. We also don't support Minecraft snapshots

**Comment by StandingPadAnimations** [comment]
Closing as won't fix

**Comment by startFX** [comment]
Hello, I have realized that this issue contains sensitive information. Is it possible to get the screeenshots removed? They’re what give away info.

**Comment by startFX** [comment]
> Hello, I have realized that this issue contains sensitive information. Is it possible to get the screeenshots removed? They’re what give away info.

I have edited the original issue to remove the images, I hope that’s all right.
