### ISSUE TITLE
Unable to add this plugin in Blender 4.0

### ISSUE THREAD

**Issue by JoKerTanser** [Moo-Ack-Productions/MCprep#580]
### Did the issue happen after restarting Blender?

- [X] Yes, the issue indeed continued after restarting Blender

### Check known issues

- [X] I have checked known issues, and my problem is different

### What happened?

Unable to add this plugin in Blender 4.0, adding this plugin will result in the following error
![Snipaste_2024-05-17_22-18-31](https://github.com/Moo-Ack-Productions/MCprep/assets/73488824/2595548a-403f-43a5-9809-33354f0a5300)

### What steps are needed to produce the bug?

Click to enable
![Snipaste_2024-05-17_22-20-05](https://github.com/Moo-Ack-Productions/MCprep/assets/73488824/29560d8f-a4fb-44eb-be70-245658292e56)

### What version of MCprep are you using?

Mcprep 3.6 RC-1

### What version of Blender are you using?

Blender 4.0

**Comment by StandingPadAnimations** [comment]
A fixed build has been uploaded, please try that
