### ISSUE TITLE
Car rig

### ISSUE THREAD

**Issue by JOTIBI** [Moo-Ack-Productions/MCprep#597]
### Check against existing requests

- [X] I have checked existing feature requests, and my idea is different

### Describe the context

A rig for a car would take MCprep to the next level. It's so inconvenient to animate the tires every time. 

### How do you imagine your feature works?

Maybe a button where you can add a car model.

### What existing workaround (or closest thing to a workaround) do you have today (within Blender, MCprep, or any software)? If there is no workaround, explain why you feel this way.

i dont understand the question?????

**Comment by StandingPadAnimations** [comment]
Cars are too far beyond the scope of vanilla Minecraft to be included in MCprep
