### ISSUE TITLE
Grass block gray layer on outside of side texture

### ISSUE THREAD

**Issue by peejcodes** [Moo-Ack-Productions/MCprep#598]
### Did the issue happen after restarting Blender?

- [X] Yes, the issue indeed continued after restarting Blender

### Check known issues

- [X] I have checked known issues, and my problem is different

### What happened?

![mcprep_grass](https://github.com/Moo-Ack-Productions/MCprep/assets/130196840/6945a253-f36e-4f2c-b1c7-655661e59d16)

So I've just been messing around with the block spawner recently and when I spawn in a grass_block model there seems to be a layer on the outside of the block showing the normal texture but gray. I can still see the green layer that's supposed to be there underneath the gray but it's almost like there's a second layer there like people have on their minecraft skins. If I go into the modeling tab I can delete the vertices for the outer layer and the block appears as it should.

### What steps are needed to produce the bug?

Open blender and use the block model spawner to spawn in grass_block and it happens. I tried this with the snowy grass block, podzol, and mycelium and none of them cause the same bug. 

### What version of MCprep are you using?

MCprep 3.5.3

### What version of Blender are you using?

Blender 4.1

**Comment by StandingPadAnimations** [comment]
Already known in #510, closing in favor of that
