### ISSUE TITLE
Item Textures not loading

### ISSUE THREAD

**Issue by LiDevils** [Moo-Ack-Productions/MCprep#606]
### Did the issue happen after restarting Blender?

- [X] Yes, the issue indeed continued after restarting Blender

### Check known issues

- [X] I have checked known issues, and my problem is different

### What happened?

I'm not sure if this is user error or not, but I can't load the minecraft textures for items or blocks at all. Mob textures work fine. I place the item, and click imrpove UI and it doesn't work. I'm not sure If I am just missing a step or not. 

### What steps are needed to produce the bug?

1) Placing down items in the "Item spawner" tab 
2) Scrolling up and clicking "Improve UI" 

### What version of MCprep are you using?

Mcprep 3.5.3

### What version of Blender are you using?

Blender 4.2

**Comment by StandingPadAnimations** [comment]
Are you in material mode or have texture view enabled in solid view?
![image](https://github.com/user-attachments/assets/f9242f85-5c81-4317-9938-9858c8ba9ade)

**Comment by LiDevils** [comment]
I just enabled texture view and nothing changed, and I have tried Material Mode and still nothing.

**Comment by Aspirata** [comment]
Use cycles when spawning an item or download Mcprep PR2+

**Comment by LiDevils** [comment]
Thank you so much! Using cycles instantly fixed my problem!
