### ISSUE TITLE
Remove leftover optimizer references in prep mats

### ISSUE THREAD

**Issue by TheDuckCow** [Moo-Ack-Productions/MCprep#618]
So far the most common bug report we have with the new version is due to some left over code of the optimizer. I guess we didn't test every permutation of settings 🤷 

At this point, we have 35 users who have encountered this error:

```
^^^^^^^^^^^^^^^^^^^^^^^
 File "<addon_path>/prep.py", line 302, in execute
 bpy.ops.mcprep.optimize_scene()
 File "<addon_path>/ops.py", line 109, in __call__
 ret = _op_call(self.idname_py(), kw)
 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 AttributeError: Calling operator "bpy.ops.mcprep.optimize_scene" error, could not be found

```

Due to the following lines (though we should also just remove the optimize checkmark everywhere too); doing a search, I don't see any other places where `optimize_scene` is used

```python
		if self.optimizeScene and engine == 'CYCLES':
			bpy.ops.mcprep.optimize_scene()
```

**Comment by TheDuckCow** [comment]
This is the most common report, and given that Prep materials is the most common feature, probably warrants doing a patch within the next 7 days for v3.6.1,  but we can see if there are any other reports that come through. Will be good to get in a cadence of faster response micro patches! Expecting we'll push out most of the other tasks in the v3.6.1 milestone to v3.6.2

I also see this error popup, but I wonder if it's due to people who installed MCprep and didn't restart right away, since I believe we _did_ resolve this issue (but maybe sanity check me @StandingPadAnimations in case we think this is another issue).

```
^^^^^^^^^^^^^^^^^^^^^^^
 File "<addon_path>/effects.py", line 1057, in execute
 add_geonode_area_effect(context, effect)
 File "<addon_path>/effects.py", line 113, in add_geonode_area_effect
 geo_update_params(context, effect, geo_mod)
 File "<addon_path>/effects.py", line 469, in geo_update_params
 geo_mod[geo_inp_id[inp.name]] = value
 ~~~~~~~^^^^^^^^^^^^^^^^^^^^^^
 TypeError: Cannot assign a 'float' value to the existing 'Input_18' Boolean IDProperty


```

**Comment by StandingPadAnimations** [comment]
> (and amongst those one-off errors is this one `File "<addon_path>/generate.py", line 985, in texgen_specular\n links.new(nodeSaturateMix.outputs[saturateMixOut[0]], i)\nRuntimeError: 错误: 相同的输入 / 输出接口方向\n\n` which is a good reminder to not attempt to parse error strings directly and have a consistent time across users...)

We don't translate Python errors in MCprep though. I think what's happening is Python is translating the error based on what Blender has set

**Comment by StandingPadAnimations** [comment]
Translating the error given, it seems to be one of those occasional IO errors we get for some reason (Blender-side to be clear, not our end)
![Screenshot_20240812_155024_Mull](https://github.com/user-attachments/assets/2214dc8f-4731-4d4e-9ad9-d3ec0f321ead)

**Comment by StandingPadAnimations** [comment]
Assuming those are the only issues, and the type error is from users thar haven't updated, I think it's safe to close this as completed
