### ISSUE TITLE
Problem with choosing an exporter

### ISSUE THREAD

**Issue by batonchick1** [Moo-Ack-Productions/MCprep#621]
### Did the issue happen after restarting Blender?

- [X] Yes, the issue indeed continued after restarting Blender

### Check known issues

- [X] I have checked known issues, and my problem is different

### What happened?

Hi! After the update, the map exporter selection stopped working, but everything is set up and worked before the update.
![mineways](https://github.com/user-attachments/assets/63cea866-67fb-411f-a7d4-827cf00e1d02)

### What steps are needed to produce the bug?

This becomes apparent immediately when you start the blender.

### What version of MCprep are you using?

MCprep 3.6.0

### What version of Blender are you using?

Blender 4.2

**Comment by StandingPadAnimations** [comment]
This is intended behavior as per [CommonMCOBJ](https://github.com/Moo-Ack-Productions/MCprep/issues/553). OBJs exported with CommonMCOBJ metadata (Mineways 11.07+ or jmc2OBJ 124+) now declare what exporter they were exported with, which MCprep uses. In addition, MCprep also now attaches the assumed exporter (which would have previously been used to set the option in question) to the object itself. 

Thus, as of MCprep 3.6, the explicit exporter options are now considered legacy, and only exist for supporting pre-MCprep 3.6 files. All options are made visible with an OBJ (or part of an OBJ) selected explicitly (although there are some UI things we're fixing, like #620)
